Update conditional_stuff.yml

diff --git a/.github/workflows/conditional_stuff.yml b/.github/workflows/conditional_stuff.yml
--- a/.github/workflows/conditional_stuff.yml
+++ b/.github/workflows/conditional_stuff.yml
@@ -15,10 +15,22 @@ jobs:
     steps: 
       - name: yes was passed in as 'fail_my_step'
         if: inputs.fail_my_step == 'yes'
-        run: echo "you said yes!"
+        run: echo 'you said yes!'
 
       - name: no was passed in as 'fail_my_step'
         if: inputs.fail_my_step == 'no'
-        run: echo "you said no!"
+        run: echo 'you said no!'
     
-          
+      - name: Step that may fail
+        shell: bash
+        run: |
+          echo "Hello, I may fail"
+          if [ "yes" = "${{ inputs.fail_my_step }}" ]; then
+            exit 42
+          fi
+
+      - name: Another step
+        run: echo "another step..."
+        
+      - name: Another step
+        run: echo "another step..."
